# conf/llm/default.yaml - Default LLM configuration
provider: "openai" # openai, anthropic, qwen
model_name: "gpt-4o"
async_client: false
temperature: 0.3
top_p: 1.0
min_p: 0.0
top_k: -1
max_tokens: 4096
api_key: "sk-1d5bvZ7FBiHekMSUOtbATIVTjkfd7fBQfWnbU1VDxTmsm2ky"
base_url: http://14.103.68.46/v1
keep_tool_result: -1
repetition_penalty: 1.0
stream: true
max_context_length: 128000
